name: Merge "hotfix/**" into "main" and "develop"

on:
  pull_request:
    branches:
      - main
      - hotfix/**
    types:
      - closed

jobs:
  merge_hotfix_into_main_and_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Merge hotfix into main and develop
        uses: devmasx/merge-branch@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: develop
          from_branch: main
          message: "Github Actions: Merge hotfix into main and develop"
          # main_branch: main
          # develop_branch: develop
          # branch_prefix: hotfix

      # - name: Merge hotfix into main and develop
      #   run: |
      #     git checkout main
      #     git merge --no-ff origin/hotfix
      #     git push origin main
      #     git checkout develop
      #     git merge --no-ff origin/hotfix
      #     git push origin develop
